import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/provider";
import { amiri } from "@/lib/fonts";

export const metadata: Metadata = {
  title: {
    template: "%s | Blog Cms",
    default: "Blog Cms"
  },
  description: "Generated by Biramahire Dan Bellamy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${amiri.className} bg-amber-50 text-black dark:text-white dark:bg-slate-900`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
