import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Provider from "@/components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog Cms",
  description: "Generated by Biramahire Dan Bellamy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-amber-50 text-black dark:text-amber-50 dark:bg-slate-900`}
      >
        <Provider>
          <Header />
          <main className="max-w-5xl mx-auto h-auto px-6">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
